// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njmhhrxuzorutndsdzmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qbWhocnh1em9ydXRuZHNkem1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNDU1NTMsImV4cCI6MjA3MjgyMTU1M30.9uEWFUT-reNA9OlZ8GbdxWTqM51pE_d2Hg8vdEqfTfE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});